### ISSUE TITLE
App Installer emitting a "The XML in the .appinstaller file is not valid: Line 70 Column 2. Reason: Unexpected end of input. (0xC00CEE01)" on many machines

### ISSUE THREAD

**Issue by nbevans** [MicrosoftDocs/msix-docs#191] opened 2020-10-29 12:24 UTC
![image](https://user-images.githubusercontent.com/542188/97573080-1f654a80-19e1-11eb-944f-4d9d7a2a4834.png)

`The XML in the .appinstaller file is not valid: Line 70 Column 2. Reason: Unexpected end of input. (0xC00CEE01)`

We released an update of our app and lots of machines encountered this problem. We found that rebooting the machine solved it.

It seems like App Installer is holding some sort of cache of .appinstaller files and that this cache was somehow corrupted by the new .appinstaller? That's my theory.

**As a potential (unverified) workaround** we have added a `Cache-Control: no-cache, max-age=0` header to the .appinstaller file which is hosted on an Azure Blob Storage account.

Last month we had a similar issue:

`The XML in the .appinstaller file is not valid: Line 14, Column 11, Reason: '>' expected. (0xC00CEE23)`

This seems to be very similar issue, and I found two threads:

https://techcommunity.microsoft.com/t5/msix-deployment/windows-10-2004-msix-not-updating-please-check-whether-the/m-p/1466701/page/2

https://techcommunity.microsoft.com/t5/msix-deployment/error-0xc00cee23-when-minor-version-gt-10/m-p/1780808#.X4dBZY6BG74.link

... one of the workarounds somebody posted was the same as ours for 0xC00CEE01: reboot the machine.

Other people in that thread are suggesting that a version number higher than 10 is causing it. I do not believe this - I think this theory comes as a result of the file size having changed by 1 byte by part of the version number having increased from 1 digit to 2 digits. Which would actually make sense because the previous version of our app was 1.2010.602.0. The new version is 1.2010.2301.0 (i.e. one byte longer). I think this is enough to cause some sort of weird cache corruption issue deep inside the App Installer implementation. I therefore really hope that it honours the Cache-Control header so that we have a workaround.

Summary:
It really does seem like some sort of cache corruption issue is causing these two error codes.

**Comment by nbevans** [comment] 2020-10-30 09:30
Update: We've now seen one machine where rebooting does not clear this error. No workaround currently known.

**Comment by wcarle** [comment] 2021-04-09 02:16
I was having this same issue and can confirm that it appears to be a cache issue.
I'm hosting the installer file in a google cloud storage bucket and despite having the cache control headers set to `private, max-age=0, no-transform` on the appinstaller file in the cloud bucket the installer still appears to be grabbing an older version.

To confirm this I changed to a slightly different path and re-uploaded the installer and it all worked correctly. I'm guessing as soon as I update the version number to the point where it reaches another digit it will probably break again

**Comment by nbevans** [comment] 2021-04-24 06:14
@chendrixson

**Comment by ranm-msft** [comment] 2021-04-28 03:31
The issue is fixed and will be out in the next Windows release.

**Comment by nbevans** [comment] 2021-05-06 17:15
Thanks - good to know. Which release of Windows will that be?

**Comment by ranm-msft** [comment] 2021-05-06 20:25
October release.

**Comment by wjkelley** [comment] 2021-06-01 20:58
Is there any documentation on a proposed workaround? We have tried adding headers to prevent caching but in our experience the only reliable workaround is to restart the Delivery Optimization service or reboot the affected machine.

**Comment by samiranshah** [comment] 2021-07-14 22:01
@wjkelley there's no workaround for this issue besides reboot.

**Comment by samiranshah** [comment] 2021-07-14 22:02
Closing for now. Please reopen if you have further questions.

**Closed by samiranshah** 2021-07-14 22:02 UTC

**Comment by ranm-msft** [comment] 2021-10-31 00:16
Yes, please let us know if you hit any issue.

**Comment by matachi** [comment] 2021-12-28 09:54
Rebooting the computer fixed the problem for me.

**Comment by noxish** [comment] 2022-01-11 09:50
> Rebooting the computer fixed the problem for me.

Thanks that fixed it on my machines

**Comment by benaclejames** [comment] 2023-04-26 23:54
Same here, a shame that this is the "fix" for the moment. I still get a lot of users submitting bug reports for my app's installer with the xml parsing error. Looks quite unprofessional to ask them to reboot their machine just to install my app

**Comment by florelis** [comment] 2023-04-27 00:28
@benaclejames 
If the cause of this is what I think it is, besides rebooting, another workaround is to keep the file size of the .appinstaller the same across versions. There is an actual fix on the OS side that is available in some versions of Windows, but it hasn't been serviced to all older versions.
