### ISSUE TITLE
Configuration of MIME types in .Net Core ASP web site 

### ISSUE THREAD

**Issue by marosklempa** [MicrosoftDocs/msix-docs#88] opened 2019-12-21 09:35 UTC
This process not working on newest Microsoft web technology .Net Core. Web site build using .Net Core ASP ignore web.config static content mimeMap. Thus if you click on link which download installer from web sire, installation will not work because web server will return 404 status (non existent file).
To proper configuration of .Net Core web site which will host your MSIX installation you need modify Configure method in Startup.cs file.
Instead of app.UseStaticFile() you have to use
var provider = new FileExtensionContentTypeProvider();
provider.Mappings.Add(".appx", "application/appx");
provider.Mappings.Add(".msix", "application/msix");
app.UseStaticFiles(new StaticFileOptions
{
    ContentTypeProvider = provider
});

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e3e8fa8-f317-6a6c-4e06-882d8e99228b
* Version Independent ID: 9e464179-5d56-2895-0117-1de7a02c5714
* Content: [Creating MSIX package with MSIX Core from source code - MSIX](https://docs.microsoft.com/en-us/windows/msix/msix-core/msixcore-clickonce-solution)
* Content Source: [msix-src/msix-core/msixcore-clickonce-solution.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/msix-core/msixcore-clickonce-solution.md)
* Product: **msix**
* GitHub Login: @dianmsft
* Microsoft Alias: **diahar**

**Comment by KevinLaMS** [comment] 2020-03-31 17:55
This is a duplicate of issue 87.

**Closed by KevinLaMS** 2020-03-31 17:55 UTC
