### ISSUE TITLE
AutomaticBackgroundTask & ForceUpdateFromAnyVersion

### ISSUE THREAD

**Issue by driesvandamme** [MicrosoftDocs/msix-docs#10] opened 2019-02-07 09:07 UTC
ForceUpdateFromAnyVersion & AutomaticBackgroundTask can't be used in combination?

When using AutomaticBackgroundTask (and triggering it by running the Scheduled task taking care of it) it doesn't take lower versions into account. Only when a higher version was published, it downloads & installs the update...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e69e20f-7cfc-aa28-85b8-f2deb8a69873
* Version Independent ID: c3fffd4b-4405-c347-2db8-95c5c0928de5
* Content: [App Installer file update settings - MSIX](https://docs.microsoft.com/en-us/windows/msix/app-installer/update-settings)
* Content Source: [msix-src/app-installer/update-settings.md](https://github.com/microsoftdocs/msix-docs/blob/master/msix-src/app-installer/update-settings.md)
* Product: **msix**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment] 2019-02-07 23:46
Thanks for reporting this. I followed up with the engineering team and confirmed that they have not seen this issue. Can you confirm that you have incremented the Version attribute of the AppInstaller element? The appinstaller version itself still needs to be incremented for the update to work – for example, appinstaller v1 containing app v5 installed, then replace appinstaller file with appinstaller v2 containing app v4.

**Comment by driesvandamme** [comment] 2019-02-08 08:09
In our example, we let the appinstaller be generated by Visual Studio (uses the same version number as the Package itself) - So no, we didn't. - Will try this and let you know - Thank you for the suggestion!

**Comment by mcleanbyron** [comment] 2019-02-08 16:21
Thanks for the follow up. Since this does not appear to be related to a docs issue at this time, I'm going to close this issue for now. Please feel to reopen if you feel you are running into a docs issue after all.

**Closed by mcleanbyron** 2019-02-08 16:21 UTC
